// ============================================================
//  AMALGAMATED FILE
//  Generated by Amalgamator v0.1.0
//  Date: 2026-05-08 13:34:22
//  Language: c
//  Source files: 2
//  Source directory: C:/Users/sir/Desktop/amalgamator/tests/fixtures/preprocessor_test
//
//  Files (in merge order):
//    - src/stm32.h
//    - src/main.c
// ============================================================

// ──────────────────────────────────────────────────
// ══════ src/stm32.h ══════
// ──────────────────────────────────────────────────
#line 1 "C:/Users/sir/Desktop/amalgamator/tests/fixtures/preprocessor_test/src/stm32.h"

int stm32_init() {
    return 32;
}



// ──────────────────────────────────────────────────
// ══════ src/main.c ══════
// ──────────────────────────────────────────────────
#line 1 "C:/Users/sir/Desktop/amalgamator/tests/fixtures/preprocessor_test/src/main.c"

#include <stdio.h>

// [amalgamator: inactive]
// [amalgamator] stripped: #include "stm32.h"
// [amalgamator: inactive]

// [amalgamator: inactive]
// [amalgamator: inactive]
// [amalgamator: inactive]

int main() {
// [amalgamator: inactive]
    printf("STM32 Init: %d\n", stm32_init());
// [amalgamator: inactive]

// [amalgamator: inactive]
// [amalgamator: inactive]
// [amalgamator: inactive]
    return 0;
}

