// ============================================================
//  AMALGAMATED FILE
//  Generated by Amalgamator v0.1.0
//  Date: 2026-05-08 11:59:40
//  Language: c
//  Source files: 3
//  Source directory: C:/Users/sir/Desktop/amalgamator/tests/fixtures/c_project
//
//  Files (in merge order):
//    - utils.h
//    - utils.c
//    - main.c
// ============================================================

// ──────────────────────────────────────────────────
// ══════ utils.h ══════
// ──────────────────────────────────────────────────
#line 1 "C:/Users/sir/Desktop/amalgamator/tests/fixtures/c_project/utils.h"


int add(int a, int b);
int multiply(int a, int b);




// ──────────────────────────────────────────────────
// ══════ utils.c ══════
// ──────────────────────────────────────────────────
#line 1 "C:/Users/sir/Desktop/amalgamator/tests/fixtures/c_project/utils.c"

// [amalgamator] stripped: #include "utils.h"

int add(int a, int b) {
    return a + b;
}

int multiply(int a, int b) {
    return a * b;
}



// ──────────────────────────────────────────────────
// ══════ main.c ══════
// ──────────────────────────────────────────────────
#line 1 "C:/Users/sir/Desktop/amalgamator/tests/fixtures/c_project/main.c"

#include <stdio.h>
// [amalgamator] stripped: #include "utils.h"

int main() {
    int a = 5, b = 3;
    printf("Add: %d + %d = %d\n", a, b, add(a, b));
    printf("Multiply: %d * %d = %d\n", a, b, multiply(a, b));
    printf("Amalgamator works!\n");
    return 0;
}

